language: ruby
rvm:
  - 2.2
env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # Speeds up installation of html-proofer
before_install:
  - gem install html-proofer
script:
    - bundle exec jekyll build
    - htmlproofer ./_site --disable-external --check-html
