# Dependencies
markdown:         redcarpet
redcarpet:
  extensions: ["tables"]

pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            'Devillers - Freelance Software Architect'
url:              http://www.devillers.nl

paginate:         5
paginate_path: 	  "/blog/page:num/"

# Custom vars
version:          1.0.0

github:
  repo:           github.com/MartinDevillers/MartinDevillers.github.io

gems:
  - jekyll-redirect-from

# Travis bundles all gems in the vendor directory on its build servers, which Jekyll will mistakenly read and explode on.
exclude: [vendor]