# Dependencies
markdown:         kramdown
highlighter:      rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge

# Permalinks
permalink:        pretty

# Setup
title:            'Devillers - Freelance Software Engineer'
url:              https://www.devillers.nl

paginate:         5
paginate_path: 	  "/blog/page:num/"

# Custom vars
version:          1.0.0

github:
  repo:           github.com/MartinDevillers/MartinDevillers.github.io

plugins:
  - jekyll-redirect-from
  - jekyll-paginate

# Travis bundles all plugins in the vendor directory on its build servers, which Jekyll will mistakenly read and explode on.
exclude: [vendor]

t:
  nl:
    zoeken: Zoeken
    telefoon: Telefoon
    adres: Adres
    contactgegevens: Contactgegevens
    allerechtenvoorbehouden: Alle rechten voorbehouden.
  en:
    zoeken: Search
    telefoon: Telephone
    adres: Address
    contactgegevens: Contactdetails
    allerechtenvoorbehouden: All rights reserved.

placeholder_image: data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 138 100'%3E%3C/svg%3E
empty_image: data:image/gif;base64,R0lGODlhAQABAIAAAP///wAAACH5BAEAAAAALAAAAAABAAEAAAICRAEAOw==
